## mega65-shell — QMTECH Wukong static (thin shell) constraints
##
## Generated from WUKONG.xdc for the shell_top/rm_top hierarchy:
##  * shell_clk_base, video_out_clock, ddr3_wrapper, reset_manager moved from
##    i_framework/... to the shell top level
##  * The core framework (QNICE etc.) lives inside the RM at
##    RM/i_framework/...
##  * core_clk0 / core_clk1 are the generic outputs of i_shell_core_clk
##    (boundary v2 dual-MMCM topology; CORE_A boots at 54 MHz democore preset)
## Pin constraints are identical to WUKONG.xdc.
##
## QMTECH Wukong board (XC7A100T-2FGG676)
##
## Pin data taken from mega65-core-wukong's wukong.xdc; timing constraints
## adapted from MiSTer2MEGA65's common.xdc (which this file replaces here:
## do NOT add common.xdc to a Wukong build, the MEGA65 HyperRAM constraints
## in there do not apply).
##
## Wukong port done by 0xa000 in 2026; SPDX-License-Identifier: LGPL-3.0-or-later

################################
## TIMING CONSTRAINTS
################################

## System board clock (50 MHz)
create_clock -period 20.000 -name clk [get_ports {clk_in}]

## Name Autogenerated Clocks
create_generated_clock -name sys_clk_100    [get_pins i_clk_wukong/i_pll_sys/CLKOUT0]
create_generated_clock -name loader_clk     [get_pins i_shell_clk_base/i_pll_base/CLKOUT0]
create_generated_clock -name audio_clk      [get_pins i_shell_clk_base/i_clk_audio/CLKOUT0]
create_generated_clock -name tmds_clk       [get_pins i_video_out_clock/MMCM/CLKOUT0]
create_generated_clock -name hdmi_clk       [get_pins i_video_out_clock/MMCM/CLKOUT1]
create_generated_clock -name ddr3_clk       [get_pins i_ddr3_wrapper/i_mmcm_ddr3/CLKOUT0]
create_generated_clock -name ddr3_clk_90    [get_pins i_ddr3_wrapper/i_mmcm_ddr3/CLKOUT1]
## The UberDDR3 controller clock is the shell's mem domain (single clock,
## no CDC in the Avalon memory chain); shell_clk_base's 100 MHz output is unused
create_generated_clock -name mem_clk        [get_pins i_ddr3_wrapper/i_mmcm_ddr3/CLKOUT2]
create_generated_clock -name ddr3_ref_clk   [get_pins i_ddr3_wrapper/i_mmcm_ddr3/CLKOUT3]

## Core-clock service (boundary v2): CORE_A and CORE_B MMCM outputs + mux outputs.
## Static build times the DEFAULT table: CORE_A at 54 MHz (democore preset),
## CORE_B fed from clk_100 (cascade off, forced below by case analysis).
## Child XDCs override per the one-table rule (BOUNDARY-V2.md §Build-time STA).
create_generated_clock -name core_a_clk0 [get_pins i_shell_core_clk/i_core_a/CLKOUT0]
create_generated_clock -name core_a_clk1 [get_pins i_shell_core_clk/i_core_a/CLKOUT1]
create_generated_clock -name core_a_clk2 [get_pins i_shell_core_clk/i_core_a/CLKOUT2]

## Cascade mux: STA sees only the default input (clk_100 -> CORE_B). Without
## this, two clocks reach CORE_B/CLKIN1 and its auto-derived output clocks
## become ambiguous. clkctl_accepted[2] resets to 0 and is quasi-static.
set_case_analysis 0 [get_pins {clkctl_accepted_reg[2]/Q}]
create_generated_clock -name core_b_clk0 [get_pins i_shell_core_clk/i_core_b/CLKOUT0]
create_generated_clock -name core_b_clk1 [get_pins i_shell_core_clk/i_core_b/CLKOUT1]
create_generated_clock -name core_b_clk2 [get_pins i_shell_core_clk/i_core_b/CLKOUT2]

## Output muxes (BUFGMUX_CTRL -> BUFGCTRL): both candidate clocks are timed,
## declared physically exclusive (only one drives the net at a time) — the
## UG903 clock-multiplexer idiom, same setup flat C64 flicker-fix needs.
## Generic outputs, no swap: core_clk0 <- CLKOUT0 (core_?_clk0, fractional-
## capable), core_clk1 <- CLKOUT1 (core_?_clk1, integer only).  masters match
## the muxed source (see shell_core_clk.vhd).
create_generated_clock -name core_clk0 -divide_by 1 -add \
   -source [get_pins i_shell_core_clk/i_mux_clk0/I0] \
   -master_clock core_a_clk0 [get_pins i_shell_core_clk/i_mux_clk0/O]
create_generated_clock -name core_clk0_b -divide_by 1 -add \
   -source [get_pins i_shell_core_clk/i_mux_clk0/I1] \
   -master_clock core_b_clk0 [get_pins i_shell_core_clk/i_mux_clk0/O]
create_generated_clock -name core_clk1 -divide_by 1 -add \
   -source [get_pins i_shell_core_clk/i_mux_clk1/I0] \
   -master_clock core_a_clk1 [get_pins i_shell_core_clk/i_mux_clk1/O]
create_generated_clock -name core_clk1_b -divide_by 1 -add \
   -source [get_pins i_shell_core_clk/i_mux_clk1/I1] \
   -master_clock core_b_clk1 [get_pins i_shell_core_clk/i_mux_clk1/O]
create_generated_clock -name core_clk2 -divide_by 1 -add \
   -source [get_pins i_shell_core_clk/i_mux_clk2/I0] \
   -master_clock core_a_clk2 [get_pins i_shell_core_clk/i_mux_clk2/O]
create_generated_clock -name core_clk2_b -divide_by 1 -add \
   -source [get_pins i_shell_core_clk/i_mux_clk2/I1] \
   -master_clock core_b_clk2 [get_pins i_shell_core_clk/i_mux_clk2/O]
set_clock_groups -physically_exclusive \
   -group [get_clocks core_clk0] -group [get_clocks core_clk0_b]
set_clock_groups -physically_exclusive \
   -group [get_clocks core_clk1] -group [get_clocks core_clk1_b]
set_clock_groups -physically_exclusive \
   -group [get_clocks core_clk2] -group [get_clocks core_clk2_b]

## clkctl mux selects and MMCM RSTs are quasi-static (64-cycle stability
## filter in the shell); BUFGMUX_CTRL switches glitch-free on async selects.
## Note: BUFGMUX_CTRL elaborates to BUFGCTRL, whose select pins are S0/S1.
## (MMCM RST pins are async, not timing endpoints — no constraint needed)
set_false_path -to [get_pins i_shell_core_clk/i_mux_clk0/S*]
set_false_path -to [get_pins i_shell_core_clk/i_mux_clk1/S*]
set_false_path -to [get_pins i_shell_core_clk/i_mux_clk2/S*]

## The following constraints are needed by rtl/common/video_out_clock.vhd
## (the video MMCM is driven by the 100 MHz PLL output, not the board clock pin)
create_generated_clock -name div_clk -source [get_pins i_clk_wukong/i_pll_sys/CLKOUT0] -divide_by 2 [get_pins i_video_out_clock/clki_div_reg/Q]
set_case_analysis 1 [get_pins i_video_out_clock/clk_mux_reg/Q]

## The high level reset signals are slow enough so that we can afford a false path
set_false_path -from [get_pins i_reset_manager/reset_shell_n_o_reg/C]
set_false_path -from [get_pins i_reset_manager/reset_core_n_o_reg/C]

## Generic CDC
set_max_delay 8 -datapath_only -from [get_generated_clocks] -to [get_pins -hierarchical "*cdc_stable_gen.dst_*_d_reg[*]/D"]
set_max_delay 8 -datapath_only -from [get_clocks sys_clk_100] -to [get_pins -hierarchical "*cdc_stable_gen.dst_*_d_reg[*]/D"]

################################################################################
# RM-framework constraints (e.g. QNICE sdcard_clk, EAE multicycles) live in
# the RM framework repo (constraint-ownership rule): this file may constrain
# only the static region and the boundary. The per-RM framework XDC is
# read with -unmanaged at the link stages so nothing RM-internal gets baked
# into static_locked.dcp (unmanaged constraints are not written into
# checkpoints — the bake is what errored the menu RM link on sdcard_clk).
################################################################################

################################################################################
# ASCAL
################################################################################

set_false_path -quiet -from [get_pins -hierarchical -regexp ".*/i_ascal/i_.*_reg.*/C"]   -to [get_pins -hierarchical -regexp ".*/i_ascal/avl_.*_reg.*/D"]
set_false_path -quiet -from [get_pins -hierarchical -regexp ".*/i_ascal/i_.*_reg.*/C"]   -to [get_pins -hierarchical -regexp ".*/i_ascal/o_.*_reg.*/D"]
set_false_path -quiet -from [get_pins -hierarchical -regexp ".*/i_ascal/avl_.*_reg.*/C"] -to [get_pins -hierarchical -regexp ".*/i_ascal/o_.*_reg.*/D"]
set_false_path -quiet -from [get_pins -hierarchical -regexp ".*/i_ascal/o_.*_reg.*/C"]   -to [get_pins -hierarchical -regexp ".*/i_ascal/i_.*_reg.*/D"]
set_false_path -quiet -from [get_pins -hierarchical -regexp ".*/i_ascal/o_.*_reg.*/C"]   -to [get_pins -hierarchical -regexp ".*/i_ascal/avl_.*_reg.*/D"]

set_false_path -from [get_clocks hdmi_clk]  -to [get_clocks audio_clk]
set_false_path -from [get_clocks audio_clk] -to [get_clocks hdmi_clk]
set_false_path -from [get_clocks loader_clk] -to [get_clocks hdmi_clk]
## NOTE: the ascal reset_na false path and the DDR3 IOSERDES_train LOCs only
## resolve on the synthesized netlist; they are applied in wukong-build.tcl
## after synth_design (search for apply_post_synth_constraints).

################################################################################
# DDR3 (UberDDR3)
################################################################################

set_property INTERNAL_VREF 0.675 [get_iobanks 16]

## Margin insurance: the previous static locked in WNS +0.010 on an
## mem_clk-internal controller path (stage2_bank -> o_wb_stall) — met, but a
## whisker from the edge and frozen into every child once the static locks.
## Ask the tools for a little headroom so rebuild seed noise cannot flip it.
set_clock_uncertainty -setup 0.100 [get_clocks mem_clk]

################################
## PIN ASSIGNMENTS
################################

## System clock
set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVCMOS33} [get_ports clk_in];

## Buttons
set_property -dict {PACKAGE_PIN H7  IOSTANDARD LVCMOS33} [get_ports reset_button];
set_property -dict {PACKAGE_PIN M6  IOSTANDARD LVCMOS33} [get_ports restore_key ];

## LEDs
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports led0];
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports led1];

## SD-card interface
set_property -dict {PACKAGE_PIN J8 IOSTANDARD LVCMOS33} [get_ports int_sd_mosi ];
set_property -dict {PACKAGE_PIN L4 IOSTANDARD LVCMOS33} [get_ports int_sd_clock];
set_property -dict {PACKAGE_PIN J6 IOSTANDARD LVCMOS33} [get_ports int_sd_reset];
set_property -dict {PACKAGE_PIN M5 IOSTANDARD LVCMOS33} [get_ports int_sd_miso ];

## USB serial interface
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports uart_txd];
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS33} [get_ports rsrx    ];

## QSPI config flash (pin data from mega65-core-wukong wukong.xdc; the flash
## clock is the dedicated CCLK pin, driven through STARTUPE2 — no user pin)
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports {qspi_db[0]}];
set_property -dict {PACKAGE_PIN R15 IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports {qspi_db[1]}];
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports {qspi_db[2]}];
set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports {qspi_db[3]}];
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33                } [get_ports qspi_csn    ];

## HDMI interface
set_property -dict {PACKAGE_PIN C4 IOSTANDARD TMDS_33} [get_ports tmds_clk_n      ];
set_property -dict {PACKAGE_PIN D4 IOSTANDARD TMDS_33} [get_ports tmds_clk_p      ];
set_property -dict {PACKAGE_PIN D1 IOSTANDARD TMDS_33} [get_ports {tmds_data_n[0]}];
set_property -dict {PACKAGE_PIN E1 IOSTANDARD TMDS_33} [get_ports {tmds_data_p[0]}];
set_property -dict {PACKAGE_PIN E2 IOSTANDARD TMDS_33} [get_ports {tmds_data_n[1]}];
set_property -dict {PACKAGE_PIN F2 IOSTANDARD TMDS_33} [get_ports {tmds_data_p[1]}];
set_property -dict {PACKAGE_PIN G1 IOSTANDARD TMDS_33} [get_ports {tmds_data_n[2]}];
set_property -dict {PACKAGE_PIN G2 IOSTANDARD TMDS_33} [get_ports {tmds_data_p[2]}];

## C64 keyboard interface on J12
set_property -dict {PACKAGE_PIN AB26 IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports {portb_pins[3]}]; # J12:3  | IO_L3P_T0_DQS_13
set_property -dict {PACKAGE_PIN AB24 IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports {portb_pins[6]}]; # J12:5  | IO_L9P_T1_DQS_13
set_property -dict {PACKAGE_PIN AA24 IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports {portb_pins[5]}]; # J12:7  | IO_L7P_T1_13
set_property -dict {PACKAGE_PIN AA22 IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports {portb_pins[4]}]; # J12:9  | IO_L8P_T1_13
set_property -dict {PACKAGE_PIN Y25  IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports {portb_pins[7]}]; # J12:11 | IO_L5P_T0_13
set_property -dict {PACKAGE_PIN W25  IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports {portb_pins[2]}]; # J12:13 | IO_L4P_T0_13
set_property -dict {PACKAGE_PIN Y22  IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports {portb_pins[1]}]; # J12:15 | IO_L11P_T1_SRCC_13
set_property -dict {PACKAGE_PIN W21  IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports {portb_pins[0]}]; # J12:17 | IO_L14P_T2_SRCC_13
set_property -dict {PACKAGE_PIN V26  IOSTANDARD LVCMOS33 DRIVE 16       } [get_ports {porta_pins[0]}]; # J12:19 | IO_L2P_T0_13
set_property -dict {PACKAGE_PIN U25  IOSTANDARD LVCMOS33 DRIVE 16       } [get_ports {porta_pins[6]}]; # J12:21 | IO_L1P_T0_13
set_property -dict {PACKAGE_PIN V24  IOSTANDARD LVCMOS33 DRIVE 16       } [get_ports {porta_pins[5]}]; # J12:23 | IO_L6P_T0_13
set_property -dict {PACKAGE_PIN V23  IOSTANDARD LVCMOS33 DRIVE 16       } [get_ports {porta_pins[4]}]; # J12:25 | IO_L10P_T1_13
set_property -dict {PACKAGE_PIN V18  IOSTANDARD LVCMOS33 DRIVE 16       } [get_ports {porta_pins[3]}]; # J12:27 | IO_L19P_T3_13
set_property -dict {PACKAGE_PIN U22  IOSTANDARD LVCMOS33 DRIVE 16       } [get_ports {porta_pins[2]}]; # J12:29 | IO_L12P_T1_MRCC_13
set_property -dict {PACKAGE_PIN U21  IOSTANDARD LVCMOS33 DRIVE 16       } [get_ports {porta_pins[1]}]; # J12:31 | IO_L13P_T2_MRCC_13
set_property -dict {PACKAGE_PIN T20  IOSTANDARD LVCMOS33 DRIVE 16       } [get_ports {porta_pins[7]}]; # J12:33 | IO_L15P_T2_DQS_13

## Control port 1 (PMOD) (J10)
set_property -dict {PACKAGE_PIN D5 IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports fa_up   ]; # J10:1
set_property -dict {PACKAGE_PIN G5 IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports fa_left ]; # J10:2
set_property -dict {PACKAGE_PIN E5 IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports fa_down ]; # J10:7
set_property -dict {PACKAGE_PIN E6 IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports fa_right]; # J10:8
set_property -dict {PACKAGE_PIN D6 IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports fa_fire ]; # J10:9

## Control port 2 (PMOD) (J11)
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports fb_up   ]; # J11:1
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports fb_left ]; # J11:2
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports fb_down ]; # J11:7
set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports fb_right]; # J11:8
set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports fb_fire ]; # J11:9

## DDR3 256MB (Micron MT41K128M16JT-125:K)
set_property -dict {PACKAGE_PIN E17 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_addr[0]} ];
set_property -dict {PACKAGE_PIN G17 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_addr[1]} ];
set_property -dict {PACKAGE_PIN F17 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_addr[2]} ];
set_property -dict {PACKAGE_PIN C17 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_addr[3]} ];
set_property -dict {PACKAGE_PIN G16 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_addr[4]} ];
set_property -dict {PACKAGE_PIN D16 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_addr[5]} ];
set_property -dict {PACKAGE_PIN H16 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_addr[6]} ];
set_property -dict {PACKAGE_PIN E16 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_addr[7]} ];
set_property -dict {PACKAGE_PIN H14 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_addr[8]} ];
set_property -dict {PACKAGE_PIN F15 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_addr[9]} ];
set_property -dict {PACKAGE_PIN F20 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_addr[10]}];
set_property -dict {PACKAGE_PIN H15 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_addr[11]}];
set_property -dict {PACKAGE_PIN C18 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_addr[12]}];
set_property -dict {PACKAGE_PIN G15 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_addr[13]}];
set_property -dict {PACKAGE_PIN B17 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_ba[0]}   ];
set_property -dict {PACKAGE_PIN D18 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_ba[1]}   ];
set_property -dict {PACKAGE_PIN A17 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_ba[2]}   ];
set_property -dict {PACKAGE_PIN B19 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_cas_n}   ];
set_property -dict {PACKAGE_PIN F19 IOSTANDARD DIFF_SSTL135 SLEW FAST} [get_ports {ddr3_clk_n}   ];
set_property -dict {PACKAGE_PIN F18 IOSTANDARD DIFF_SSTL135 SLEW FAST} [get_ports {ddr3_clk_p}   ];
set_property -dict {PACKAGE_PIN E18 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_cke}     ];
set_property -dict {PACKAGE_PIN A22 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_dm[0]}   ];
set_property -dict {PACKAGE_PIN C22 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_dm[1]}   ];
set_property -dict {PACKAGE_PIN D21 IOSTANDARD SSTL135      SLEW FAST IN_TERM UNTUNED_SPLIT_50} [get_ports {ddr3_dq[0]}   ];
set_property -dict {PACKAGE_PIN C21 IOSTANDARD SSTL135      SLEW FAST IN_TERM UNTUNED_SPLIT_50} [get_ports {ddr3_dq[1]}   ];
set_property -dict {PACKAGE_PIN B22 IOSTANDARD SSTL135      SLEW FAST IN_TERM UNTUNED_SPLIT_50} [get_ports {ddr3_dq[2]}   ];
set_property -dict {PACKAGE_PIN B21 IOSTANDARD SSTL135      SLEW FAST IN_TERM UNTUNED_SPLIT_50} [get_ports {ddr3_dq[3]}   ];
set_property -dict {PACKAGE_PIN D19 IOSTANDARD SSTL135      SLEW FAST IN_TERM UNTUNED_SPLIT_50} [get_ports {ddr3_dq[4]}   ];
set_property -dict {PACKAGE_PIN E20 IOSTANDARD SSTL135      SLEW FAST IN_TERM UNTUNED_SPLIT_50} [get_ports {ddr3_dq[5]}   ];
set_property -dict {PACKAGE_PIN C19 IOSTANDARD SSTL135      SLEW FAST IN_TERM UNTUNED_SPLIT_50} [get_ports {ddr3_dq[6]}   ];
set_property -dict {PACKAGE_PIN D20 IOSTANDARD SSTL135      SLEW FAST IN_TERM UNTUNED_SPLIT_50} [get_ports {ddr3_dq[7]}   ];
set_property -dict {PACKAGE_PIN C23 IOSTANDARD SSTL135      SLEW FAST IN_TERM UNTUNED_SPLIT_50} [get_ports {ddr3_dq[8]}   ];
set_property -dict {PACKAGE_PIN D23 IOSTANDARD SSTL135      SLEW FAST IN_TERM UNTUNED_SPLIT_50} [get_ports {ddr3_dq[9]}   ];
set_property -dict {PACKAGE_PIN B24 IOSTANDARD SSTL135      SLEW FAST IN_TERM UNTUNED_SPLIT_50} [get_ports {ddr3_dq[10]}  ];
set_property -dict {PACKAGE_PIN B25 IOSTANDARD SSTL135      SLEW FAST IN_TERM UNTUNED_SPLIT_50} [get_ports {ddr3_dq[11]}  ];
set_property -dict {PACKAGE_PIN C24 IOSTANDARD SSTL135      SLEW FAST IN_TERM UNTUNED_SPLIT_50} [get_ports {ddr3_dq[12]}  ];
set_property -dict {PACKAGE_PIN C26 IOSTANDARD SSTL135      SLEW FAST IN_TERM UNTUNED_SPLIT_50} [get_ports {ddr3_dq[13]}  ];
set_property -dict {PACKAGE_PIN A25 IOSTANDARD SSTL135      SLEW FAST IN_TERM UNTUNED_SPLIT_50} [get_ports {ddr3_dq[14]}  ];
set_property -dict {PACKAGE_PIN B26 IOSTANDARD SSTL135      SLEW FAST IN_TERM UNTUNED_SPLIT_50} [get_ports {ddr3_dq[15]}  ];
set_property -dict {PACKAGE_PIN A20 IOSTANDARD DIFF_SSTL135 SLEW FAST IN_TERM UNTUNED_SPLIT_50} [get_ports {ddr3_dqs_n[0]}];
set_property -dict {PACKAGE_PIN B20 IOSTANDARD DIFF_SSTL135 SLEW FAST IN_TERM UNTUNED_SPLIT_50} [get_ports {ddr3_dqs_p[0]}];
set_property -dict {PACKAGE_PIN A24 IOSTANDARD DIFF_SSTL135 SLEW FAST IN_TERM UNTUNED_SPLIT_50} [get_ports {ddr3_dqs_n[1]}];
set_property -dict {PACKAGE_PIN A23 IOSTANDARD DIFF_SSTL135 SLEW FAST IN_TERM UNTUNED_SPLIT_50} [get_ports {ddr3_dqs_p[1]}];
set_property -dict {PACKAGE_PIN G19 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_odt}     ];
set_property -dict {PACKAGE_PIN A19 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_ras_n}   ];
set_property -dict {PACKAGE_PIN H17 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_reset_n} ];
set_property -dict {PACKAGE_PIN A18 IOSTANDARD SSTL135      SLEW FAST} [get_ports {ddr3_we_n}    ];

################################
## CONFIGURATION AND BITSTREAM PROPERTIES
################################

set_property CONFIG_VOLTAGE                  3.3     [current_design]
set_property CFGBVS                          VCCO    [current_design]
set_property BITSTREAM.GENERAL.COMPRESS      TRUE    [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE     50      [current_design]
set_property CONFIG_MODE                     SPIx4   [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH   4       [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN      PULLUP  [current_design]
